# Generated by Django 4.0.6 on 2022-07-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_name', models.CharField(max_length=20)),
                ('Age', models.CharField(max_length=10)),
                ('Desg', models.CharField(max_length=20)),
            ],
        ),
    ]
